[package]
name = "vulkano-www"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
publish = false

[dependencies]
lazy_static = "0.2"
markdown = "0.2.0"
mustache = "0.8"
rouille = "1.0"
