version: 2

jobs:

  test:
    working_directory: ~/tgst
    docker:
      - image: mackeyja92/rustup
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -yq sudo curl wget git file g++ cmake pkg-config bison flex unzip lib32stdc++6 lib32z1
      - checkout
      - run: cargo test

  deploy:
    working_directory: ~/tgst
    docker:
      - image: mackeyja92/rustup
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -yq sudo curl wget git file g++ cmake pkg-config bison flex unzip lib32stdc++6 lib32z1
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Push Docker image to registry
          command: |
            docker build -t $DOCKER_IMAGE_TAG .
            docker login -u $DOCKER_REGISTRY_LOGIN -p $DOCKER_REGISTRY_PASS $DOCKER_REGISTRY_URL
            docker push $DOCKER_IMAGE_TAG  
      - run:
          name: Send restart command
          command: |
            curl --request POST $MARATHON_URL/v2/apps/$MARATHON_APP_ID/restart

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
